/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model.field;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class InvoiceNumber implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String invoiceNumber;
    private String collectiveInvoiceNumber;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(invoiceNumber != null) {
            nodeWriter.write(delimiters.escape(invoiceNumber.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(collectiveInvoiceNumber != null) {
            nodeWriter.write(delimiters.escape(collectiveInvoiceNumber.toString()));
        }
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public InvoiceNumber setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;  return this;
    }

    public String getCollectiveInvoiceNumber() {
        return collectiveInvoiceNumber;
    }

    public InvoiceNumber setCollectiveInvoiceNumber(String collectiveInvoiceNumber) {
        this.collectiveInvoiceNumber = collectiveInvoiceNumber;  return this;
    }
}