/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model.field;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class ServiceGroup implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String billingCode;
    private String rateIndicator;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(billingCode != null) {
            nodeWriter.write(delimiters.escape(billingCode.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(rateIndicator != null) {
            nodeWriter.write(delimiters.escape(rateIndicator.toString()));
        }
    }

    public String getBillingCode() {
        return billingCode;
    }

    public ServiceGroup setBillingCode(String billingCode) {
        this.billingCode = billingCode;  return this;
    }

    public String getRateIndicator() {
        return rateIndicator;
    }

    public ServiceGroup setRateIndicator(String rateIndicator) {
        this.rateIndicator = rateIndicator;  return this;
    }
}