/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Bes implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String totalGrossAmount;
    private String amountLegalAdditionalPayment;
    private String totalAmountLegalAdditionalPayment;
    private String allInAdditionalPayment;
    private String totalAmountDeductible;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(totalGrossAmount != null) {
            nodeWriter.write(delimiters.escape(totalGrossAmount.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(amountLegalAdditionalPayment != null) {
            nodeWriter.write(delimiters.escape(amountLegalAdditionalPayment.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(totalAmountLegalAdditionalPayment != null) {
            nodeWriter.write(delimiters.escape(totalAmountLegalAdditionalPayment.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(allInAdditionalPayment != null) {
            nodeWriter.write(delimiters.escape(allInAdditionalPayment.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(totalAmountDeductible != null) {
            nodeWriter.write(delimiters.escape(totalAmountDeductible.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getTotalGrossAmount() {
        return totalGrossAmount;
    }

    public Bes setTotalGrossAmount(String totalGrossAmount) {
        this.totalGrossAmount = totalGrossAmount;  return this;
    }

    public String getAmountLegalAdditionalPayment() {
        return amountLegalAdditionalPayment;
    }

    public Bes setAmountLegalAdditionalPayment(String amountLegalAdditionalPayment) {
        this.amountLegalAdditionalPayment = amountLegalAdditionalPayment;  return this;
    }

    public String getTotalAmountLegalAdditionalPayment() {
        return totalAmountLegalAdditionalPayment;
    }

    public Bes setTotalAmountLegalAdditionalPayment(String totalAmountLegalAdditionalPayment) {
        this.totalAmountLegalAdditionalPayment = totalAmountLegalAdditionalPayment;  return this;
    }

    public String getAllInAdditionalPayment() {
        return allInAdditionalPayment;
    }

    public Bes setAllInAdditionalPayment(String allInAdditionalPayment) {
        this.allInAdditionalPayment = allInAdditionalPayment;  return this;
    }

    public String getTotalAmountDeductible() {
        return totalAmountDeductible;
    }

    public Bes setTotalAmountDeductible(String totalAmountDeductible) {
        this.totalAmountDeductible = totalAmountDeductible;  return this;
    }
}