/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Fkt implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String processingFlag;
    private String collectiveInvoice;
    private String billerIK;
    private String receiverIK;
    private String healthInsuranceIK;
    private String senderIK;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(processingFlag != null) {
            nodeWriter.write(delimiters.escape(processingFlag.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(collectiveInvoice != null) {
            nodeWriter.write(delimiters.escape(collectiveInvoice.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(billerIK != null) {
            nodeWriter.write(delimiters.escape(billerIK.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(receiverIK != null) {
            nodeWriter.write(delimiters.escape(receiverIK.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(healthInsuranceIK != null) {
            nodeWriter.write(delimiters.escape(healthInsuranceIK.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(senderIK != null) {
            nodeWriter.write(delimiters.escape(senderIK.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getProcessingFlag() {
        return processingFlag;
    }

    public Fkt setProcessingFlag(String processingFlag) {
        this.processingFlag = processingFlag;  return this;
    }

    public String getCollectiveInvoice() {
        return collectiveInvoice;
    }

    public Fkt setCollectiveInvoice(String collectiveInvoice) {
        this.collectiveInvoice = collectiveInvoice;  return this;
    }

    public String getBillerIK() {
        return billerIK;
    }

    public Fkt setBillerIK(String billerIK) {
        this.billerIK = billerIK;  return this;
    }

    public String getReceiverIK() {
        return receiverIK;
    }

    public Fkt setReceiverIK(String receiverIK) {
        this.receiverIK = receiverIK;  return this;
    }

    public String getHealthInsuranceIK() {
        return healthInsuranceIK;
    }

    public Fkt setHealthInsuranceIK(String healthInsuranceIK) {
        this.healthInsuranceIK = healthInsuranceIK;  return this;
    }

    public String getSenderIK() {
        return senderIK;
    }

    public Fkt setSenderIK(String senderIK) {
        this.senderIK = senderIK;  return this;
    }
}