/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Ges implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String status;
    private String totalInvoiceAmount;
    private String totalGrossAmount;
    private String additionalPayment;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(status != null) {
            nodeWriter.write(delimiters.escape(status.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(totalInvoiceAmount != null) {
            nodeWriter.write(delimiters.escape(totalInvoiceAmount.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(totalGrossAmount != null) {
            nodeWriter.write(delimiters.escape(totalGrossAmount.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(additionalPayment != null) {
            nodeWriter.write(delimiters.escape(additionalPayment.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getStatus() {
        return status;
    }

    public Ges setStatus(String status) {
        this.status = status;  return this;
    }

    public String getTotalInvoiceAmount() {
        return totalInvoiceAmount;
    }

    public Ges setTotalInvoiceAmount(String totalInvoiceAmount) {
        this.totalInvoiceAmount = totalInvoiceAmount;  return this;
    }

    public String getTotalGrossAmount() {
        return totalGrossAmount;
    }

    public Ges setTotalGrossAmount(String totalGrossAmount) {
        this.totalGrossAmount = totalGrossAmount;  return this;
    }

    public String getAdditionalPayment() {
        return additionalPayment;
    }

    public Ges setAdditionalPayment(String additionalPayment) {
        this.additionalPayment = additionalPayment;  return this;
    }
}