/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Inv implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String insuranceNumber;
    private String insuredStatus;
    private String freeField;
    private String documentNumber;
    private String plateSpecialCareForm;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(insuranceNumber != null) {
            nodeWriter.write(delimiters.escape(insuranceNumber.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(insuredStatus != null) {
            nodeWriter.write(delimiters.escape(insuredStatus.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(freeField != null) {
            nodeWriter.write(delimiters.escape(freeField.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(documentNumber != null) {
            nodeWriter.write(delimiters.escape(documentNumber.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(plateSpecialCareForm != null) {
            nodeWriter.write(delimiters.escape(plateSpecialCareForm.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getInsuranceNumber() {
        return insuranceNumber;
    }

    public Inv setInsuranceNumber(String insuranceNumber) {
        this.insuranceNumber = insuranceNumber;  return this;
    }

    public String getInsuredStatus() {
        return insuredStatus;
    }

    public Inv setInsuredStatus(String insuredStatus) {
        this.insuredStatus = insuredStatus;  return this;
    }

    public String getFreeField() {
        return freeField;
    }

    public Inv setFreeField(String freeField) {
        this.freeField = freeField;  return this;
    }

    public String getDocumentNumber() {
        return documentNumber;
    }

    public Inv setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;  return this;
    }

    public String getPlateSpecialCareForm() {
        return plateSpecialCareForm;
    }

    public Inv setPlateSpecialCareForm(String plateSpecialCareForm) {
        this.plateSpecialCareForm = plateSpecialCareForm;  return this;
    }
}