/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.smooks.edi.EDIMessage;    
import java.util.List;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

@EDIMessage    
public class InvoiceMessage implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private Unb unb;
    private List<Unhs> unhs;
    private Unz unz;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(unb != null) {
            nodeWriter.write("UNB");
            nodeWriter.write(delimiters.getField());
            unb.write(nodeWriter, delimiters);
        }
        if(unhs != null && !unhs.isEmpty()) {
            for(Unhs unhsInst : unhs) {
                unhsInst.write(nodeWriter, delimiters);
            }
        }
        if(unz != null) {
            nodeWriter.write("UNZ");
            nodeWriter.write(delimiters.getField());
            unz.write(nodeWriter, delimiters);
        }
    }

    public Unb getUnb() {
        return unb;
    }

    public InvoiceMessage setUnb(Unb unb) {
        this.unb = unb;  return this;
    }

    public List<Unhs> getUnhs() {
        return unhs;
    }

    public InvoiceMessage setUnhs(List<Unhs> unhs) {
        this.unhs = unhs;  return this;
    }

    public Unz getUnz() {
        return unz;
    }

    public InvoiceMessage setUnz(Unz unz) {
        this.unz = unz;  return this;
    }
}