/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import io.github.weissmuster.edi.invoice.model.field.InvoiceNumber;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Rec implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private InvoiceNumber invoiceNumber;
    private String date;
    private String invoiceType;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(invoiceNumber != null) {
            invoiceNumber.write(nodeWriter, delimiters);
        }
        nodeWriter.write(delimiters.getField());
        if(date != null) {
            nodeWriter.write(delimiters.escape(date.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(invoiceType != null) {
            nodeWriter.write(delimiters.escape(invoiceType.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public InvoiceNumber getInvoiceNumber() {
        return invoiceNumber;
    }

    public Rec setInvoiceNumber(InvoiceNumber invoiceNumber) {
        this.invoiceNumber = invoiceNumber;  return this;
    }

    public String getDate() {
        return date;
    }

    public Rec setDate(String date) {
        this.date = date;  return this;
    }

    public String getInvoiceType() {
        return invoiceType;
    }

    public Rec setInvoiceType(String invoiceType) {
        this.invoiceType = invoiceType;  return this;
    }
}