/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.invoice.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Unz implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String numberOfMessages;
    private String icrn;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(numberOfMessages != null) {
            nodeWriter.write(delimiters.escape(numberOfMessages.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(icrn != null) {
            nodeWriter.write(delimiters.escape(icrn.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getNumberOfMessages() {
        return numberOfMessages;
    }

    public Unz setNumberOfMessages(String numberOfMessages) {
        this.numberOfMessages = numberOfMessages;  return this;
    }

    public String getIcrn() {
        return icrn;
    }

    public Unz setIcrn(String icrn) {
        this.icrn = icrn;  return this;
    }
}