/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model.field;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class MessageIdentifier implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String type;
    private String version;
    private String typeReleaseNumber;
    private String administrativeOrganisation;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(type != null) {
            nodeWriter.write(delimiters.escape(type.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(version != null) {
            nodeWriter.write(delimiters.escape(version.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(typeReleaseNumber != null) {
            nodeWriter.write(delimiters.escape(typeReleaseNumber.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(administrativeOrganisation != null) {
            nodeWriter.write(delimiters.escape(administrativeOrganisation.toString()));
        }
    }

    public String getType() {
        return type;
    }

    public MessageIdentifier setType(String type) {
        this.type = type;  return this;
    }

    public String getVersion() {
        return version;
    }

    public MessageIdentifier setVersion(String version) {
        this.version = version;  return this;
    }

    public String getTypeReleaseNumber() {
        return typeReleaseNumber;
    }

    public MessageIdentifier setTypeReleaseNumber(String typeReleaseNumber) {
        this.typeReleaseNumber = typeReleaseNumber;  return this;
    }

    public String getAdministrativeOrganisation() {
        return administrativeOrganisation;
    }

    public MessageIdentifier setAdministrativeOrganisation(String administrativeOrganisation) {
        this.administrativeOrganisation = administrativeOrganisation;  return this;
    }
}