/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model.field;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Syntax implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String version;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(id != null) {
            nodeWriter.write(delimiters.escape(id.toString()));
        }
        nodeWriter.write(delimiters.getComponent());
        if(version != null) {
            nodeWriter.write(delimiters.escape(version.toString()));
        }
    }

    public String getId() {
        return id;
    }

    public Syntax setId(String id) {
        this.id = id;  return this;
    }

    public String getVersion() {
        return version;
    }

    public Syntax setVersion(String version) {
        this.version = version;  return this;
    }
}