/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    
import java.io.StringWriter;    
import java.util.List;    
import java.util.ArrayList;    
import org.milyn.edisax.util.EDIUtils;    
import org.milyn.edisax.model.internal.DelimiterType;    

public class Ans implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String typeOfAddress;
    private String postalCode;
    private String city;
    private String address;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = new StringWriter();

        List<String> nodeTokens = new ArrayList<String>();

        if(typeOfAddress != null) {
            nodeWriter.write(delimiters.escape(typeOfAddress.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeWriter.write(delimiters.getField());
        if(postalCode != null) {
            nodeWriter.write(delimiters.escape(postalCode.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeWriter.write(delimiters.getField());
        if(city != null) {
            nodeWriter.write(delimiters.escape(city.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeWriter.write(delimiters.getField());
        if(address != null) {
            nodeWriter.write(delimiters.escape(address.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeTokens.add(nodeWriter.toString());
        writer.write(EDIUtils.concatAndTruncate(nodeTokens, DelimiterType.FIELD, delimiters));
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getTypeOfAddress() {
        return typeOfAddress;
    }

    public Ans setTypeOfAddress(String typeOfAddress) {
        this.typeOfAddress = typeOfAddress;  return this;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public Ans setPostalCode(String postalCode) {
        this.postalCode = postalCode;  return this;
    }

    public String getCity() {
        return city;
    }

    public Ans setCity(String city) {
        this.city = city;  return this;
    }

    public String getAddress() {
        return address;
    }

    public Ans setAddress(String address) {
        this.address = address;  return this;
    }
}