/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.util.List;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class ContactPersons implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private Nam nam;
    private List<Ans> ans;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(nam != null) {
            nodeWriter.write("NAM");
            nodeWriter.write(delimiters.getField());
            nam.write(nodeWriter, delimiters);
        }
        if(ans != null && !ans.isEmpty()) {
            for(Ans ansInst : ans) {
                nodeWriter.write("ANS");
                nodeWriter.write(delimiters.getField());
                ansInst.write(nodeWriter, delimiters);
            }
        }
    }

    public Nam getNam() {
        return nam;
    }

    public ContactPersons setNam(Nam nam) {
        this.nam = nam;  return this;
    }

    public List<Ans> getAns() {
        return ans;
    }

    public ContactPersons setAns(List<Ans> ans) {
        this.ans = ans;  return this;
    }
}