/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Fkt implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String processingFlag;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(processingFlag != null) {
            nodeWriter.write(delimiters.escape(processingFlag.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getProcessingFlag() {
        return processingFlag;
    }

    public Fkt setProcessingFlag(String processingFlag) {
        this.processingFlag = processingFlag;  return this;
    }
}