/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Uem implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String typeOfTransmissionMedium;
    private String parameter;
    private String charset;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(typeOfTransmissionMedium != null) {
            nodeWriter.write(delimiters.escape(typeOfTransmissionMedium.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(parameter != null) {
            nodeWriter.write(delimiters.escape(parameter.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(charset != null) {
            nodeWriter.write(delimiters.escape(charset.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getTypeOfTransmissionMedium() {
        return typeOfTransmissionMedium;
    }

    public Uem setTypeOfTransmissionMedium(String typeOfTransmissionMedium) {
        this.typeOfTransmissionMedium = typeOfTransmissionMedium;  return this;
    }

    public String getParameter() {
        return parameter;
    }

    public Uem setParameter(String parameter) {
        this.parameter = parameter;  return this;
    }

    public String getCharset() {
        return charset;
    }

    public Uem setCharset(String charset) {
        this.charset = charset;  return this;
    }
}