/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Una implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String field;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(field != null) {
            nodeWriter.write(delimiters.escape(field.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getField() {
        return field;
    }

    public Una setField(String field) {
        this.field = field;  return this;
    }
}