/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import io.github.weissmuster.edi.health.insurance.model.field.MessageIdentifier;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Unh implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String messageReferenceNumber;
    private MessageIdentifier messageIdentifier;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(messageReferenceNumber != null) {
            nodeWriter.write(delimiters.escape(messageReferenceNumber.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(messageIdentifier != null) {
            messageIdentifier.write(nodeWriter, delimiters);
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getMessageReferenceNumber() {
        return messageReferenceNumber;
    }

    public Unh setMessageReferenceNumber(String messageReferenceNumber) {
        this.messageReferenceNumber = messageReferenceNumber;  return this;
    }

    public MessageIdentifier getMessageIdentifier() {
        return messageIdentifier;
    }

    public Unh setMessageIdentifier(MessageIdentifier messageIdentifier) {
        this.messageIdentifier = messageIdentifier;  return this;
    }
}