/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class Unt implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String numberOfUnits;
    private String messageReferenceNumber;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(numberOfUnits != null) {
            nodeWriter.write(delimiters.escape(numberOfUnits.toString()));
        }
        nodeWriter.write(delimiters.getField());
        if(messageReferenceNumber != null) {
            nodeWriter.write(delimiters.escape(messageReferenceNumber.toString()));
        }
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getNumberOfUnits() {
        return numberOfUnits;
    }

    public Unt setNumberOfUnits(String numberOfUnits) {
        this.numberOfUnits = numberOfUnits;  return this;
    }

    public String getMessageReferenceNumber() {
        return messageReferenceNumber;
    }

    public Unt setMessageReferenceNumber(String messageReferenceNumber) {
        this.messageReferenceNumber = messageReferenceNumber;  return this;
    }
}