/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package io.github.weissmuster.edi.health.insurance.model;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    
import java.io.StringWriter;    
import java.util.List;    
import java.util.ArrayList;    
import org.milyn.edisax.util.EDIUtils;    
import org.milyn.edisax.model.internal.DelimiterType;    

public class Vdt implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private String effectiveDateFrom;
    private String effectiveDateTo;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = new StringWriter();

        List<String> nodeTokens = new ArrayList<String>();

        if(effectiveDateFrom != null) {
            nodeWriter.write(delimiters.escape(effectiveDateFrom.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeWriter.write(delimiters.getField());
        if(effectiveDateTo != null) {
            nodeWriter.write(delimiters.escape(effectiveDateTo.toString()));
            nodeTokens.add(nodeWriter.toString());
            ((StringWriter)nodeWriter).getBuffer().setLength(0);
        }
        nodeTokens.add(nodeWriter.toString());
        writer.write(EDIUtils.concatAndTruncate(nodeTokens, DelimiterType.FIELD, delimiters));
        writer.write(delimiters.getSegmentDelimiter());
        writer.flush();
    }

    public String getEffectiveDateFrom() {
        return effectiveDateFrom;
    }

    public Vdt setEffectiveDateFrom(String effectiveDateFrom) {
        this.effectiveDateFrom = effectiveDateFrom;  return this;
    }

    public String getEffectiveDateTo() {
        return effectiveDateTo;
    }

    public Vdt setEffectiveDateTo(String effectiveDateTo) {
        this.effectiveDateTo = effectiveDateTo;  return this;
    }
}